### ISSUE TITLE
more panel/status icons support 

### ISSUE THREAD

**Issue by bil-elmoussaoui** [numixproject/numix-icon-theme#394]
Hello, i add this just to add some more missing status icons/panel ones

- [x] #296 Workspace indicator (for elementary os) 
- [x] #295 Usb indicator (for ubuntu, elemntary os too)
- [x] #312 Blueman indicator 
- [x] #257 Quiterss indicator 
- [x] #265 Tomboy notes
- [x] #250  Insync indicators support 
- [x] #151  clipman indicator 
- [x] #375 Variety indicator 
- [x] #371 Copy indicators
- [x] #369  Dropbox icons
- [x] #258 Synapse indicator icon 
- [x]  #313 Improve weather status icons 
- [x] #397 todo indicator icon 
- [x] #414 Zim wiki indicator icon 
- [x] [circle/#1779](https://github.com/numixproject/numix-icon-theme-circle/issues/1779) Clementine player 
- [x] Grive indicator
- [x] #443 Privacy indicator 
- [x] #370 Hipchat status icons
- [x] #505  Netspeed indicator 
- [ ] #498 Gnome pie indicator
- [x] #128 Hexchat tray icons

Hardcoded indicators 
- [x] Pushbullet indicator
- [x] My-weather-indicator
- [x] Viber using viberwrapper-indicator : viber-normal.svg and viber-notification.svg 
- [x] Telegram
- [x] Touchpad indicator
- [x] radiotray
- [x] yd-tools

Those hardcoded indicators could be fixed using a python script : https://github.com/bil-elmoussaoui/Hardcode-Tray

I hope this list is complete ! ;) 
Thank you  @wa4557  for everything you've done to make Numix theme get better! :+1:

**Comment by wa4557** [comment]
Definitely not complete :)
I'll open an issue, maybe you can add it afterwards here. And please remove the question mark from the last point, the current weather status icons are awful imo :P

**Comment by bil-elmoussaoui** [comment]
Done ;) i will keep updating this list with any other icons; and @Foggalong are you going to support indicators like for viber,telegram,megasync even if they are hardcoded? The same thing as spotify client and much more... but you can fix that by patching sni-qt version?

**Comment by wa4557** [comment]
Another one https://github.com/numixproject/numix-icon-theme-circle/issues/1779

**Comment by dirtydancing** [comment]
@bil-elmoussaoui Hi, Blueman on your list has been fixed, cf. https://github.com/numixproject/numix-icon-theme/issues/312.

**Comment by dirtydancing** [comment]
@bil-elmoussaoui Hi, could you add (Unity) Privacy Indicator to the list please, cf. https://github.com/numixproject/numix-icon-theme/issues/443

**Comment by bil-elmoussaoui** [comment]
@dirtydancing done :)

**Comment by dirtydancing** [comment]
Great, thanks! :)

**Comment by wa4557** [comment]
@bil-elmoussaoui Could you add #128 and remove the ticks from `my-weather-indicator` `yd-tools`. They are not fixed yet (although a PR for `yd-tools` will be merged hopefully :)

**Comment by bil-elmoussaoui** [comment]
@wa4557 for my-weather-indicator a symlink in TrayHardcode will fix that nop ?

**Comment by wa4557** [comment]
Yes, but here it's about Numix and in Numix this icon is not fixed

**Comment by Foggalong** [comment]
We have the weather icons in place in Numix too. You were the one who updated them to fit the scalable Numix design, no?

**Comment by bil-elmoussaoui** [comment]
@Foggalong yeah, be we do have to fix this in the Hardcode Tray

**Comment by wa4557** [comment]
Yeah, but they are already ticked :) The problem is that my-weather-indicator (I don't use this program btw.; uses hardcoded icons)

**Comment by Foggalong** [comment]
@wa4557 @bil-elmoussaoui If we have the icons in Numix then the fixing need to be tracked separately in the Hardcode-Tray repo. We okay to tick it off? :)

**Comment by Foggalong** [comment]
Is there any more information on pomdoro too?

**Comment by wa4557** [comment]
Fine for me

**Comment by Foggalong** [comment]
Similarly, what are the icons needed for pushbullet indicator?

**Comment by bil-elmoussaoui** [comment]
The icons are 
``` 
pushbullet-indicator-dark.svg
pushbullet-indicator-sync0-dark.svg
pushbullet-indicator-sync1-dark.svg
pushbullet-indicator-sync2-dark.svg
pushbullet-indicator-sync3-dark.svg
pushbullet-indicator-light
pushbullet-indicator-sync0-light.svg
pushbullet-indicator-sync1-light.svg
pushbullet-indicator-sync2-light.svg
pushbullet-indicator-sync3-light.svg
```
For pomodoro, there's a lot of icons.. And i'm not using it anymore i prefer to fix other issues and wait until someone reports it?

**Comment by wa4557** [comment]
Ok, I will do the pushbullet ones today. Insync is a hard one however :( And for gnome-pie I have actually no idea if I should push a status icon or not :)

**Comment by Foggalong** [comment]
@bil-elmoussaoui Feel free to knock Pomodoro of the list then :)

@wa4557 From what I can see Insync isn't hardcoded? Original issue says all the icons are located in `hicolor/*`

**Comment by bil-elmoussaoui** [comment]
I do think that we can symlink Insync to Grive ?

**Comment by Foggalong** [comment]
@bil-elmoussaoui From what I can see there's very little overlap between the two icon wise :(

**Comment by wa4557** [comment]
@Foggalong What I meant is, that the insync icons are hard to do, not that they are hardcoded :) But since these are the last ones that are missing, I'll put some effort in that. Should I also push a gnome-pie icon?

**Comment by bil-elmoussaoui** [comment]
@wa4557 Thanks for the hard work, i will close this as Gnome pie have it's own issue :+1:
